# Generated by Django 2.2.3 on 2019-08-02 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
